"""
LiveKit connector orchestrator.

Manages the full lifecycle of the LiveKit transport:
  1. Starts the LiveKit server Docker container.
  2. Optionally starts the browser-facing token server (only needed when clients
     are on HTTPS and cannot connect to the LiveKit WS directly).
  3. Registers this process as a ConnectorEndpoint with the XR-Media-Hub IPC layer.
  4. Connects the Python room client to the LiveKit room.
  5. Runs the IPC return-traffic loop and the room client concurrently.

Token server is opt-in via LiveKitConnectorConfig.enable_token_server (default False).
On a local/HTTP network clients can connect directly to ws://<host>:7880 using a
token generated by livekit-api — no proxy needed.

Usage
-----
    cfg = LiveKitConnectorConfig(room_name="my-room")
    conn = LiveKitConnector(cfg)
    await conn.start()
    try:
        await conn.run()
    finally:
        await conn.stop()
"""
from __future__ import annotations

import asyncio
import logging
from typing import Awaitable, Callable

from xr_media_hub.ipc._connector import ConnectorEndpoint
from xr_media_hub.ipc._types import AudioChunk, DataMessage

from ._docker import LiveKitDocker
from ._room_client import RoomClient
from ._token_server import TokenServer
from .config import LiveKitConnectorConfig

log = logging.getLogger(__name__)

ReturnAudioCallback = Callable[[AudioChunk],  Awaitable[None]]
ReturnDataCallback  = Callable[[DataMessage], Awaitable[None]]


class LiveKitConnector:
    def __init__(self, cfg: LiveKitConnectorConfig | None = None) -> None:
        self._cfg    = cfg or LiveKitConnectorConfig()
        self._docker = LiveKitDocker(self._cfg)
        self._token  = TokenServer(self._cfg) if self._cfg.enable_token_server else None
        self._ep     = ConnectorEndpoint(
            push_addr=self._cfg.hub_push_addr,
            sub_addr=self._cfg.hub_sub_addr,
            num_slots=self._cfg.shm_num_slots,
            max_frame_bytes=self._cfg.shm_max_frame_bytes,
        )
        self._room_client = RoomClient(self._cfg, self._ep)
        self._stop = asyncio.Event()

    # ── callback registration ─────────────────────────────────────────────────

    def on_return_audio(self, cb: ReturnAudioCallback) -> None:
        """Called when the hub sends TTS/agent audio back to a participant."""
        self._ep.on_return_audio(cb)

    def on_return_data(self, cb: ReturnDataCallback) -> None:
        """Called when the hub sends agent text/binary back to a participant."""
        self._ep.on_return_data(cb)

    # ── lifecycle ─────────────────────────────────────────────────────────────

    async def start(self) -> None:
        """Start Docker, optionally token server, register IPC endpoint, connect room client."""
        await self._docker.start()
        if self._token:
            await self._token.start()
        await self._ep.register()
        await self._room_client.connect()
        log.info("LiveKitConnector started — room=%r", self._cfg.room_name)

    async def run(self) -> None:
        """
        Run IPC return-traffic loop and room client concurrently.

        Returns when stop() is called or either task raises an unhandled exception.
        """
        ipc_task  = asyncio.create_task(self._ep.run(),          name="ipc-return")
        room_task = asyncio.create_task(self._room_client.run(), name="room-client")
        try:
            done, pending = await asyncio.wait(
                [ipc_task, room_task],
                return_when=asyncio.FIRST_EXCEPTION,
            )
        except asyncio.CancelledError:
            ipc_task.cancel()
            room_task.cancel()
            await asyncio.gather(ipc_task, room_task, return_exceptions=True)
            raise

        for t in pending:
            t.cancel()
        await asyncio.gather(*pending, return_exceptions=True)

        for t in done:
            exc = t.exception()
            if exc:
                log.error("Connector task %r raised: %s", t.get_name(), exc)

    async def stop(self) -> None:
        """Gracefully shut down all components in reverse-start order."""
        log.info("LiveKitConnector stopping…")
        self._ep.stop()
        self._room_client.stop()
        await self._room_client.disconnect()
        self._ep.close()
        if self._token:
            await self._token.stop()
        await self._docker.stop()
        log.info("LiveKitConnector stopped")
